spring:
  mvc:
    throw-exception-if-no-handler-found: true # dispatcherServlet에서 알맞은 handler를 찾을 수 없을 때 NoHandlerFoundExcpetion throw
  web:
    resources:
      add-mappings: false # 기본 resouce handler disabled

server:
  error:
    whitelabel:
      enabled: false # default error page disabled
